# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
#  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
#  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
#  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Nightscout"
  org.opencontainers.image.description: "Nightscout acts as a web-based CGM (Continuous Glucose Montinor) to allow multiple caregivers to remotely view a patients glucose data in realtime."
  org.opencontainers.image.source: "https://github.com/dgcartersa/hass-addons-repository/tree/main/nightscout"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"